version: '3'

vars:
  ANSIBLE_DIR: '02_configure'

tasks:
  vyos:
    desc: "Vyos Configure"
    dir: '{{.ANSIBLE_DIR}}'
    cmds:
      - ansible-playbook playbooks/vyos.yml
  
  postgres:
    desc: "Postgres Configure"
    dir: '{{.ANSIBLE_DIR}}'
    cmds:
      - ansible-playbook playbooks/postgres.yml

  01-bootstrap:
    desc: "Run format, validation, apply and configure sequentially"
    cmds:
      - task: vyos
      - task: postgres