version: '3'

vars:
  ANSIBLE_DIR: '01_bootstrap/configure'

tasks:
  vyos:
    desc: "Vyos Configure"
    dir: '{{.ANSIBLE_DIR}}'
    cmds:
      - ansible-playbook playbooks/vyos.yml
  
  postgres:
    desc: "Postgres Configure"
    dir: '{{.ANSIBLE_DIR}}'
    cmds:
      - ansible-playbook playbooks/postgres.yml

  all:
    desc: "Run format, validation, apply and configure sequentially"
    cmds:
      - task: vyos
      - task: postgres