version: '3'

vars:
  TERRAGRUNT_DIR: '01_provision/live'

tasks:
  init:
    desc: "Terragrunt Init"
    dir: '{{.TERRAGRUNT_DIR}}'
    cmds:
      - terragrunt run --all --non-interactive -- init

  validate-00-prebootstrap:
    desc: "Terragrunt Validate Pre-Bootstrap configuration"
    dir: '{{.TERRAGRUNT_DIR}}/00_prebootstrap'
    cmds:
      - terragrunt run --non-interactive -- validate

  validate-01-bootstrap:
    desc: "Terragrunt Validate Bootstrap configuration"
    dir: '{{.TERRAGRUNT_DIR}}/01_bootstrap'
    cmds:
      - terragrunt run --non-interactive -- validate

  apply-00-prebootstrap:
    desc: "Terragrunt Apply Pre-Bootstrap"
    dir: '{{.TERRAGRUNT_DIR}}/00_prebootstrap'
    cmds:
      - terragrunt run --non-interactive -- apply -auto-approve

  apply-01-bootstrap:
    desc: "Terragrunt Apply Bootstrap"
    dir: '{{.TERRAGRUNT_DIR}}/01_bootstrap'
    cmds:
      - terragrunt run --non-interactive -- apply -auto-approve

  destroy:
    desc: "Terragrunt Destroy"
    dir: '{{.TERRAGRUNT_DIR}}'
    cmds:
      - terragrunt run --all --non-interactive -- destroy

  all:
    desc: "Run format, validation, apply and configure sequentially"
    cmds:
      - task: init
      - task: validate-00-prebootstrap
      - task: validate-01-bootstrap
      - task: apply-00-prebootstrap
      - task: apply-01-bootstrap
