version: '3'

includes:
  packer: tasks/packer.yml
  terragrunt: tasks/terragrunt.yml
  ansible: tasks/ansible.yml

tasks:
  bootstrap-all:
    desc: "Bootstrap all the infrastructure (Packer -> Terragrunt -> Ansible)"
    cmds:
      - task: packer:all
      - task: terragrunt:all
      - task: ansible:all

  bootstrap-destroy:
    desc: "Destroy all infrastructure and clean up state"
    cmds:
      - task: terragrunt:destroy
      - task: packer:clean