version: '3'

includes:
  packer: tasks/packer.yml
  terragrunt: tasks/terragrunt.yml
  ansible: tasks/ansible.yml

tasks:
  prebootstrap:
    desc: "Pre-bootstrap the infrastructure"
    cmds:
      - task: terragrunt:validate-00-prebootstrap
      - task: terragrunt:apply-00-prebootstrap

  bootstrap:
    desc: "Bootstrap the infrastructure (Packer -> Terragrunt -> Ansible)"
    cmds:
      - task: packer:all
      - task: terragrunt:validate-01-bootstrap
      - task: terragrunt:apply-01-bootstrap
      - task: ansible:01-bootstrap

  bootstrap-destroy:
    desc: "Destroy all infrastructure and clean up state"
    cmds:
      - task: terragrunt:destroy
      - task: packer:clean