id: 9100
name: "rocky-10.1-base"
template_name: "rocky-10.1-base"
template_description: "Rocky Linux 10.1 base image built by Packer"

iso_file: "Rocky-10.1-x86_64-minimal"
cfg_file: "ks"
boot_file: "rocky"
provisioner_file: "rocky"
network_bridge: "vmbr0"