- name: Install and configure VyOS
  hosts: host
  gather_facts: false
  connection: ansible.netcommon.network_cli
  vars:
    ansible_network_os: vyos.vyos.vyos
  vars_files:
    - ../../../config/common.yml
    - ../../../config/services/vyos.yml

  tasks:
    - name: Wait for SSH port (22) to accept connections
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 22
        state: started
        delay: 20
        timeout: 600    
      delegate_to: localhost

    - name: Load VyOS tasks
      ansible.builtin.import_tasks: ../tasks/vyos.yml